import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const jt_mono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${jt_mono.className} mx-auto flex min-h-dvh max-w-6xl flex-col text-base`}>
        <Header />
        <main className="flex grow flex-col px-10">
          <div className="h-full grow border-x border-dashed px-10 py-5">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
